name: 'epic_connector'
version: '0.1.2'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

vars:
  input_database: tuva_demo
  input_schema: epic
  
  ## validate that all seeds were populated correctly
  error_empty_seeds: true

  ## populates the tuva last run columns
  tuva_last_run: '{{ run_started_at.astimezone(modules.pytz.timezone("UTC")) }}'


  ## sets tuva to the correct model build types
  clinical_enabled: true

models:
  epic_connector:
    staging:
      +materialized: ephemeral
      +schema: epic_staging
    intermediate:
      +materialized: view
      +schema: epic_intermediate
    final:
      +materialized: table
      +schema: epic_final

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: 'dbt'
    search_order: ['the_tuva_project', 'dbt']