select 
    cast(null as varchar(50)) as claim_id,
    cast(null as int) as claim_line_number,
    cast(null as varchar(50)) as person_id,
    cast(null as varchar(50)) as member_id,
    cast(null as varchar(100)) as payer,
    cast(null as varchar(100)) as plan,
    cast(null as varchar(50)) as prescribing_provider_npi,
    cast(null as varchar(50)) as dispensing_provider_npi,
    cast(null as date) as dispensing_date,
    cast(null as varchar(100)) as ndc_code,
    cast(null as int) as quantity,
    cast(null as int) as days_supply,
    cast(null as int) as refills,
    cast(null as date) as paid_date,
    cast(null as decimal(18, 2)) as paid_amount,
    cast(null as decimal(18, 2)) as allowed_amount,
    cast(null as decimal(18, 2)) as charge_amount,
    cast(null as decimal(18, 2)) as coinsurance_amount,
    cast(null as decimal(18, 2)) as copayment_amount,
    cast(null as decimal(18, 2)) as deductible_amount,
    cast(null as int) as in_network_flag,
    cast(null as varchar(100)) as data_source,
    cast(null as varchar(255)) as file_name,
    cast(null as datetime) as ingest_datetime